<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE TranslationFile [
<!ELEMENT CQ5PageTranslation ( PageURL, PropertyContents ) >
<!ATTLIST CQ5PageTranslation Deadline CDATA #IMPLIED >
<!ATTLIST CQ5PageTranslation PagePath CDATA #REQUIRED >

<!ELEMENT CQ5PageTranslations ( CQ5PageTranslation+ ) >

<!ELEMENT PageURL ( #PCDATA ) >
<!ATTLIST PageURL ForPreviewOnly CDATA #REQUIRED >
<!ATTLIST PageURL NeedTranslation CDATA #REQUIRED >

<!ELEMENT PropertyContent ( #PCDATA | Contents )* >
<!ATTLIST PropertyContent IsMultipleValue CDATA #REQUIRED >
<!ATTLIST PropertyContent NodePath CDATA #REQUIRED >
<!ATTLIST PropertyContent PropertyName CDATA #REQUIRED >

<!ELEMENT PropertyContents ( PropertyContent+ ) >

<!ELEMENT Contents ( Content+ ) >

<!ELEMENT Content ( #PCDATA ) >
<!ATTLIST Content Order CDATA #REQUIRED ><!ELEMENT TranslationFile ( CQ5PageTranslations ) >
<!ATTLIST TranslationFile CQ5SourceLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile CQ5TargetLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile CQJobDescription CDATA #IMPLIED >
<!ATTLIST TranslationFile CQJobName CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3AssetId CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3ProjectId CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3SourceLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3TargetLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile InCountryReviewer CDATA #IMPLIED >
]>
<TranslationFile CQ5SourceLanguage="EN_ME" CQ5TargetLanguage="AR_ME" CQJobDescription="" CQJobName="Submit by [s.butt] @ 2016-06-14 5.31 AM" CT3AssetId="237c9d10-8b07-4b47-8c40-4f6945601531" CT3ProjectId="aa0a8ca1-fbe6-4567-8039-3372b10c7739" CT3SourceLanguage="en-GB" CT3TargetLanguage="ar-XR" InCountryReviewer="">
    <CQ5PageTranslations>
        <CQ5PageTranslation Deadline="07/04/2016" PagePath="/content/infiniti_master/ar_ME/index/brand-section">
            <PageURL ForPreviewOnly="True" NeedTranslation="False">http://author.prod.heliosnissan.net/content/infiniti_master/ar_ME/index/brand-section.html</PageURL>
            <PropertyContents>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="jcr:title">About Infiniti</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/title" PropertyName="txBody">We believe a luxury vehicle should connect you to the road, not insulate you from it. It should put you in charge, not take charge. It should make your heart beat faster, not lull you to sleep.Infiniti's pioneering spirit boldly breaks from convention to create something more distinctive.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/title" PropertyName="txTitle">BOLDLY BREAK AWAY</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns12_7d1c/col1-par/image_6d2c" PropertyName="txTitle">About Infiniti : Our Vision</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns12_7d1c/col1-par/image_6d2c" PropertyName="txSubTitle">LET EMOTION BE THE DRIVER</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns12_7d1c/col1-par/image_6d2c/previewImage" PropertyName="txAlt">About Infiniti</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns12_7d1c/col1-par/image_6d2c/links/link1" PropertyName="txText">See more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_5145" PropertyName="txTitle">OUR STORY</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_5145" PropertyName="txSubTitle">Timeline</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_5145/previewImage" PropertyName="txAlt">OUR STORY</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_5145/links/link1" PropertyName="txText">Read more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_96c7" PropertyName="txTitle">Infiniti F1</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_96c7" PropertyName="txSubTitle">INNOVATION NEVER STOPS</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_96c7/previewImage" PropertyName="txAlt">Infiniti F1</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col1-par/image_96c7/links/link1" PropertyName="txText">Read more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_4e2a" PropertyName="txTitle">Concept Cars</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_4e2a" PropertyName="txSubTitle">Driven By Desire</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_4e2a/previewImage" PropertyName="txAlt">Driven by desire.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_4e2a/links/link1" PropertyName="txText">Read more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_85a5" PropertyName="txTitle">Innovations</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_85a5" PropertyName="txSubTitle">FROM POWER TO SUPER POWER</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_85a5/previewImage" PropertyName="txAlt">Driven by desire.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_4a8a/col2-par/image_85a5/links/link1" PropertyName="txText">Read more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_242d" PropertyName="txTitle">New Naming Structure</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_242d" PropertyName="txSubTitle">WHEN HERITAGE DRIVES A NAME TOWARDS THE FUTURE</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_242d/previewImage" PropertyName="txAlt">New Naming Structure</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_242d/links/link1" PropertyName="txText">Read more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_d69" PropertyName="txTitle">Contact us</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_d69" PropertyName="txSubTitle">FOR ALL GENERAL CUSTOMER ENQUIRIES</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_d69/previewImage" PropertyName="txAlt">Contact us</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col1-par/image_d69/links/link1" PropertyName="txText">Read more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col2-par/image_2a99" PropertyName="txTitle">News And Events</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col2-par/image_2a99" PropertyName="txSubTitle">THE VERY LATEST FROM INFINITI</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col2-par/image_2a99/previewImage" PropertyName="txAlt">Driven by desire.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5778/columns/columns66_8a0c/col2-par/image_2a99/links/link1" PropertyName="txText">Read more</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txTitle">About Infiniti</PropertyContent>
            </PropertyContents>
        </CQ5PageTranslation>
        <CQ5PageTranslation Deadline="07/04/2016" PagePath="/content/infiniti_master/ar_ME/index/copyright">
            <PageURL ForPreviewOnly="True" NeedTranslation="False">http://author.prod.heliosnissan.net/content/infiniti_master/ar_ME/index/copyright.html</PageURL>
            <PropertyContents>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="jcr:title">Copyright</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txTitle">Copyright</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12_a80b/col1-par/heliostext_6ee8" PropertyName="txText">&lt;p style="font-family: tahoma, arial, helvetica, sans-serif; font-size: 12px;"&gt;INFINITI, the INFINITI logo, Accelerating the future, and Infiniti model names are Nissan trademarks ©2013 INFINITI Division of Nissan Middle East Freezone. All rights reserved. Materials contained on this website may not be used or reproduced without written permission from Nissan Middle East Freezone.&lt;/p&gt;&lt;p style="font-family: tahoma, arial, helvetica, sans-serif; font-size: 12px;"&gt;All illustrations, photographs and specifications on this Web site are based on the latest product information; some vehicle parts cannot be shown in certain photographs. Some vehicles shown with optional equipment. See actual vehicles for complete accuracy. INFINITI Division of Nissan Middle East Freezone. reserves the right to make changes at any time, without notice, in prices, colors, materials, equipment, specifications and models, and to discontinue models or equipment. Availability and delivery time for particular models and equipment combinations may vary. For information on availability, additional options or accessories, contact your Infiniti dealer. All specifications, options, and accessories shown on this Web site may differ in other countries. Homelink is a registered trademark of Johnson Controls, Inc. Birdview is a trademark of Xanavi Corporation. The XM name and related logos are registered trademarks of XM Satellite Radio Inc. Sirius and related marks are trademarks of Sirius Satellite Radio Inc. All rights reserved.&lt;br&gt;&lt;/p&gt;</PropertyContent>
            </PropertyContents>
        </CQ5PageTranslation>
        <CQ5PageTranslation Deadline="07/04/2016" PagePath="/content/infiniti_master/ar_ME/index/Privacy">
            <PageURL ForPreviewOnly="True" NeedTranslation="False">http://author.prod.heliosnissan.net/content/infiniti_master/ar_ME/index/Privacy.html</PageURL>
            <PropertyContents>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="pageTitle">Menu name</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="jcr:title">Privacy Policy</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="navTitle">Privacy</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_ce98" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_ce98" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_ce98/title" PropertyName="txTitle">Anonymous Information - Cookies and Log Files</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_ce98/columns/columns12_96f0/col1-par/heliostext_4697" PropertyName="txText">&lt;p&gt;&lt;p&gt;A cookie is a piece of data stored on the user's hard drive containing information about the user. Usage of a cookie is in no way linked to personal information, until a user provides that information (see below). If a user rejects or deletes the cookie, he/she may still use our site. The only drawback to this is that the user will be limited in some areas of our site. For example, the user will not be able to receive notification of special offers, or participate in any contests that may take place. Cookies also enable us to track and aggregate clickstream behavior data. By doing this we can better target the interests of our users and enhance their experience on our site.&lt;br&gt;&lt;br&gt;Infiniti also maintains standard web logs that record data about all visitors to this web site. These logs may contain:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;The Internet domain from which you access this site&lt;/li&gt;&lt;li&gt;Your IP address (Your computer is automatically assigned an IP address when you surf the Internet. Your IP address is either static or dynamic. A static IP address may be identifiable to you; a dynamic address is usually not identifiable to you)&lt;/li&gt;&lt;li&gt;The type of browser and operating system you use&lt;/li&gt;&lt;li&gt;The date and time you visited this site&lt;/li&gt;&lt;li&gt;The pages you viewed on this site&lt;/li&gt;&lt;li&gt;The address of the web site from which you linked&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Infiniti uses web log and clickstream information to help us design our site, to identify popular site features and to make the site more useful for visitors. Web logs are recorded in sequential files, and we normally do not attempt to identify individuals from these logs. However, we may use web logs to identify persons attempting to break into, disrupt, or damage our site. We may share web log information with law enforcement personnel if we believe evidence exists, or is likely to occur, of a violation of federal, state or local laws or regulations.&lt;/p&gt;&lt;br&gt;&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7911" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7911" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7911/title" PropertyName="txTitle">Security</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7911/columns/columns12_c308/col1-par/heliostext_9f9d" PropertyName="txText">&lt;p&gt;Infiniti takes all reasonable precautions to protect our users' information, both while the information is being transmitted and after it is received by us.&lt;br&gt;&lt;br&gt;Furthermore, once the information has been received by us, we use security procedures and policies commensurate with industry standards to safeguard against loss, theft, unauthorized access, destruction, use, modification and disclosure. If you have any questions about the security of our web site, you can send an e-mail to privacy@Infiniti-me.com.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_b918" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_b918" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_b918/title" PropertyName="txTitle">Links</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_b918/columns/columns12_4a54/col1-par/heliostext_d3c7" PropertyName="txText">&lt;p&gt;This web site contains links to other sites. Please be aware that Infiniti is not responsible for the privacy practices of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of each web site that collects personal information. This privacy statement applies solely to information collected by this web site.&lt;br&gt;Notification of Changes&lt;br&gt;We retain the right to change this privacy policy at any time. We will post those changes to this page so that users are always aware of what information we collect, how we use it, and under what circumstances we disclose it. We will use, share, and disclose all information in accordance with the privacy policy in effect at the time the information was collected.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_4666" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_4666" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_4666/title" PropertyName="txTitle">Certain Disclosures</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_4666/columns/columns12_9131/col1-par/heliostext_f759" PropertyName="txText">&lt;p&gt;Infiniti may disclose any data, whether personally identifiable or not, to any person performing audit, legal, services for services for Infiniti or Nissan Middle East Freezone.&lt;br&gt;&lt;br&gt;Whenever possible, we will require any recipient of personal information for these purposes to agree in writing to hold the information in confidence, to use the information only for the permitted purpose, and to return or destroy the information when the services are completed.&lt;br&gt;&lt;br&gt;We may also disclose any data, whether personally identifiable or not, when required to do so by subpoena, court order, or warrant. Whenever feasible, Infiniti will notify the affected user by e-mail that such disclosure will or has occurred.&lt;br&gt;&lt;br&gt;We may also disclose any data, whether personally identifiable or not, when we reasonably deem it necessary to protect the safety of (i) an individual, (ii) the public, or (iii) the security and reliability of Infiniti and/or this web site.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_e995" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_e995" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_e995/title" PropertyName="txTitle">Infiniti Contact Information</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_e995/columns/columns12_7b5f/col1-par/heliostext_2241" PropertyName="txText">&lt;p&gt;To contact Infiniti online, you may click on the “Contact Us” link below. To contact Infiniti offline, you can send mail to:&lt;br&gt;&lt;br&gt;Nissan Middle East Freezone&lt;br&gt;Jebel Ali Free Zone&lt;br&gt;P.O.BOX 61111&lt;br&gt;United Arab Emirates&lt;br&gt;Telephone No. +9714- 881 7500&lt;br&gt;Fax No. +9714- 881 7497&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txBodyCopy">INFINITI Division of Nissan Middle East Freezone collects information from our users at several different points on our web site. Nissan Middle East Freezone is the sole owner of the information collected on this site. We will not sell or rent this information to others. We will only share this information with our affiliates and dealers, and marketing partners contracted to do business on our behalf (e.g., brochure fulfillment).Infiniti uses two types of user information: anonymous information gathered from cookies and log files, and personal information you provide us for certain services. See below for definitions of each of these methods.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txTitle">Privacy Policy</PropertyContent>
            </PropertyContents>
        </CQ5PageTranslation>
        <CQ5PageTranslation Deadline="07/04/2016" PagePath="/content/infiniti_master/ar_ME/index/disclaimer">
            <PageURL ForPreviewOnly="True" NeedTranslation="False">http://author.prod.heliosnissan.net/content/infiniti_master/ar_ME/index/disclaimer.html</PageURL>
            <PropertyContents>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="jcr:title">Disclaimer</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txTitle">Disclaimer</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702d" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702d" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702d/title" PropertyName="txTitle">Products</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702d/columns/columns12_de2f/col1-par/heliostext_1b1e" PropertyName="txText">&lt;p&gt;All illustrations, photographs and specifications in this website are based on the latest product information; some vehicles parts cannot be shown in certain photographs. Some vehicles shown with optional equipment. See actual vehicles for complete accuracy. Infiniti reserves the right to make changes at any time, without notice, colours, materials, equipment, specifications and models, and to discontinue models or equipment. Availability and delivery time for particular models and equipment combinations may vary. For information on availability, additional options or accessories, contact your local Infiniti dealer.&lt;/p&gt;&lt;p&gt;&lt;br&gt;Infiniti is striving constantly to improve its products. Accordingly all information on this Site is subject to change at any time. The availability, specifications, and models of any items on this site are provided for general information purposes only and may be subject to restrictions or may not be current at the time you view it. Please contact your nearest Authorized Dealer, for the most correct information which may vary from those on this Site. Because of the nature of technology, the colours shown on the Site may not match the actual colours.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7373" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7373" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7373/title" PropertyName="txTitle">Risk and limitation of liability</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_7373/columns/columns12_4886/col1-par/heliostext_f38c" PropertyName="txText">&lt;p&gt;You use the Site entirely at your own risk and Infiniti makes no warranty of any kind on the use or the content of this Site which is provided “as is”. Infiniti makes no guarantee that this Site is free from bugs, errors, viruses or errors that may affect your computer. Infiniti makes no guarantee that all of the information is current on the date that you view it.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_571b" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_571b" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_571b/title" PropertyName="txTitle">Intellectual Property</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_571b/columns/columns12_4886/col1-par/heliostext_f38c" PropertyName="txText">&lt;p&gt;All Intellectual Property Rights relating to this Site and its content are either the property of, or used with permission by, Infiniti. You must not copy, publish or modify anything on the Site or re-sell any of the information that you have viewed or printed from it without Infiniti’s permission. You are granted the right only to view the Site and print material from it for your personal use and/or for you to make informed decisions about Infiniti’s products.  The Infiniti names, logos, product names, feature names, and slogans are trademarks owned by or used with permission by&amp;nbsp;Nissan Motor Co. Ltd. and/or Infiniti. All rights reserved.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702/title" PropertyName="txTitle">Links</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702/columns/columns12_4886/col1-par/heliostext_f38c" PropertyName="txText">&lt;p&gt;This Site may contain links to third party sites which are completely independent from this Site. In no event shall Infiniti be responsible of the content, use or availability of any such third party site. Links to any third party site are provided for your convenience only with no guarantee whatsoever from Infiniti. Any third party links to this Site must be subject to prior written approval by Infiniti.&lt;br&gt;&lt;br&gt;The provisions set out in these Terms apply to anyone who accesses this Site regardless of their place of residence. Unless otherwise stated, these provisions apply to all services and information disclosed on the pages of the Site.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_702/columns/columns12_4886/col1-par/heliostext_f38c" PropertyName="txLinkTitle1">Privacy Policy</PropertyContent>
            </PropertyContents>
        </CQ5PageTranslation>
    </CQ5PageTranslations>
</TranslationFile>
