<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE TranslationFile [
<!ELEMENT CQ5PageTranslation ( PageURL, PropertyContents ) >
<!ATTLIST CQ5PageTranslation Deadline CDATA #IMPLIED >
<!ATTLIST CQ5PageTranslation PagePath CDATA #REQUIRED >

<!ELEMENT CQ5PageTranslations ( CQ5PageTranslation+ ) >

<!ELEMENT PageURL ( #PCDATA ) >
<!ATTLIST PageURL ForPreviewOnly CDATA #REQUIRED >
<!ATTLIST PageURL NeedTranslation CDATA #REQUIRED >

<!ELEMENT PropertyContent ( #PCDATA | Contents )* >
<!ATTLIST PropertyContent IsMultipleValue CDATA #REQUIRED >
<!ATTLIST PropertyContent NodePath CDATA #REQUIRED >
<!ATTLIST PropertyContent PropertyName CDATA #REQUIRED >

<!ELEMENT PropertyContents ( PropertyContent+ ) >

<!ELEMENT Contents ( Content+ ) >

<!ELEMENT Content ( #PCDATA ) >
<!ATTLIST Content Order CDATA #REQUIRED ><!ELEMENT TranslationFile ( CQ5PageTranslations ) >
<!ATTLIST TranslationFile CQ5SourceLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile CQ5TargetLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile CQJobDescription CDATA #IMPLIED >
<!ATTLIST TranslationFile CQJobName CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3AssetId CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3ProjectId CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3SourceLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile CT3TargetLanguage CDATA #REQUIRED >
<!ATTLIST TranslationFile InCountryReviewer CDATA #IMPLIED >
]>
<TranslationFile CQ5SourceLanguage="EN_ME" CQ5TargetLanguage="AR_ME" CQJobDescription="" CQJobName="Submit by [s.butt] @ 2016-06-27 8.17 AM" CT3AssetId="108967a3-e9ad-443d-ac98-af061f16bb42" CT3ProjectId="28773ea7-966b-4e07-9779-0320cecccb96" CT3SourceLanguage="en-GB" CT3TargetLanguage="ar-XR" InCountryReviewer="">
    <CQ5PageTranslations>
        <CQ5PageTranslation Deadline="07/17/2016" PagePath="/content/infiniti_master/ar_ME/index/vehicles/new-vehicles/Q60-Coupe-UK-2014/performance">
            <PageURL ForPreviewOnly="True" NeedTranslation="False">http://author.prod.heliosnissan.net/content/infiniti_master/ar_ME/index/vehicles/new-vehicles/Q60-Coupe-UK-2014/performance.html</PageURL>
            <PropertyContents>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="jcr:title">Performance</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txTitle">Performance</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/title" PropertyName="txBody">Free your senses and they will reward you with exhilaration, one thrilling kilometer after another.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/title" PropertyName="txTitle">Engine</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/columns/togglecontainer_3346" PropertyName="txTitle">I want a</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/columns/togglecontainer_3346/toggle/title" PropertyName="txBody">The robust design, impressive power and exceptional fuel efficiency of an Infiniti engine delivers an uncommonly smooth and refined performance. Factor in the advanced precision of Variable Valve Event and Lift (VVEL®) technology and the possibilities seem limitless. All it takes is a tap of the accelerator.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/columns/togglecontainer_3346/toggle/title" PropertyName="txDropDownTitle">PETROL</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/columns/togglecontainer_3346/toggle/title" PropertyName="txTitle">3.7-LITRE V6 ENGINE</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/columns/togglecontainer_3346/toggle/title" PropertyName="txSubTitle">PETROL</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/columns/togglecontainer_3346/toggle/toggle-columns/columns12bleed_4ef7/toggle-col1-par/image_22d2" PropertyName="txReference">front action mountain</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_df8d/columns/togglecontainer_3346/toggle/toggle-columns/columns12bleed_4ef7/toggle-col1-par/image_22d2" PropertyName="txAlt">front action mountain</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/title" PropertyName="txBody">Connect fully to your vehicle and bring more out of yourself and your drive.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/title" PropertyName="txTitle">Performance Features</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_9dfb/carousel-col1-par/image_e989" PropertyName="txBody">&lt;p&gt;A potent blend of exciting response andintelligent efficiency. Benefitting from Variable Valve Event andLift (VVEL) technology, the engine adjusts on the fly to makethe most of every bit of fuel and every breath it takes. The resultis a stirring 329 horsepower that still manages to achieve upto 8.7l/100km*.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_9dfb/carousel-col1-par/image_e989" PropertyName="txTitle">3.7-LITRE V6 ENGINE</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_9dfb/carousel-col1-par/image_e989/previewImage" PropertyName="txAlt">Rear 3/4 Action</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_d5c3/carousel-col1-par/image_e989" PropertyName="txBody">&lt;p&gt;When you flick the magnesium paddle shifter for alower gear, Downshift Rev Matching blips the throttle to ready theengine for the new gear. It gives you the power of expert performancedriving by delivering smoother, quicker downshifts for increasedstability and more consistent engine power.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_d5c3/carousel-col1-par/image_e989" PropertyName="txTitle">SHARPER SHIFTS</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_d5c3/carousel-col1-par/image_e989/previewImage" PropertyName="txAlt">Paddle Shifter Detail</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_7330/carousel-col1-par/image_e989" PropertyName="txBody">&lt;p&gt;adjust damping forcesbased on road conditions to maintain the perfect ride and preciseresponse that suits all your moments behind the wheel.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_7330/carousel-col1-par/image_e989" PropertyName="txTitle">DUAL FLOW PATH® SHOCK ABSORBERS</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_7330/carousel-col1-par/image_e989/previewImage" PropertyName="txAlt">Rear Action Mountain Road</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_acf3/carousel-col1-par/image_e989" PropertyName="txBody">&lt;p&gt;A performance car speaks to youthrough its exhaust, and the specialty exhaust tuning on theQ60 Convertible and Coupe shapes that sound into somethinguniquely compelling. Not only does it make an Infiniti unmistakable,it makes every trip up and down the tachometer an experiencethat transcends engineering and enters the realm of pure emotion.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_acf3/carousel-col1-par/image_e989" PropertyName="txTitle">THE SOUND OF PERFORMANCE</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_acf3/carousel-col1-par/image_e989/previewImage" PropertyName="txAlt">Rear static</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_302a/carousel-col1-par/image_e989" PropertyName="txBody">&lt;p&gt;Dynamic handling is built rightinto the foundation of the Q60 Convertible and Coupe, thanksto its Front-Midship Platform. Placing the engine’s center ofmass just behind the front wheel center line creates a near-equalfront-to-rear weight ratio, with a slight front bias that you’ll feelas quicker turn-in and even balance as you accelerate out of acorner.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_302a/carousel-col1-par/image_e989" PropertyName="txTitle">INNATELY RESPONSIVE BALANCE</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_a976/columns/contentcarousel_cb25/carousel-columns/columns6_302a/carousel-col1-par/image_e989/previewImage" PropertyName="txAlt">Rear Aerial Mountain</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_bba3/col1-par/linkspanel_3c95" PropertyName="txHeadline">start your journey</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_bba3/col1-par/linkspanel_3c95/cta1" PropertyName="txText">book a test drive</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_bba3/col1-par/linkspanel_3c95/cta2" PropertyName="txText">brochure</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_bba3/col1-par/linkspanel_3c95/cta3" PropertyName="txText">find a dealer</PropertyContent>
            </PropertyContents>
        </CQ5PageTranslation>
        <CQ5PageTranslation Deadline="07/14/2016" PagePath="/content/infiniti_master/ar_ME/index/careers">
            <PageURL ForPreviewOnly="True" NeedTranslation="False">http://author.prod.heliosnissan.net/content/infiniti_master/ar_ME/index/careers.html</PageURL>
            <PropertyContents>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="jcr:title">Careers</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txTitle">Careers</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_70bd" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_70bd" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_70bd/columns/columns12_94b4/col1-par/heliostext_5648" PropertyName="txText">&lt;p&gt;The Infiniti ethos is all about being forward-thinking, innovative, passionate and original. So if you share our philosophy and drive – and have the desire, expertise and curiosity to join a company that refuses to conform – you may be interested in one of our vacant positions.&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;As well as a desire to become part of a company that’s unrestricted by rules and conventions, you will need to be English-speaking with an international profile.&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;With headquarters in Switzerland, we aim to recruit sales forces in individual countries and are looking for people capable of bringing our exclusive brand experience to life as we continue to create ever more inspirational vehicles.&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;Enquiries will be treated in strictest confidence.&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_70bd/columns/columns12_94b4/col1-par/heliostext_5648" PropertyName="txTitle">THE FUTURE OF PERFORMANCE MOTORING COULD BE IN YOUR HANDS</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_70bd/columns/columns12_94b4/col1-par/heliostext_212" PropertyName="txText">&lt;p&gt;Unfortunately, there are currently no positions available with Infiniti Europe. However, please do check again soon.&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_70bd/columns/columns12_94b4/col1-par/heliostext_212" PropertyName="txTitle">CURRENT OPPORTUNITIES</PropertyContent>
            </PropertyContents>
        </CQ5PageTranslation>
        <CQ5PageTranslation Deadline="07/17/2016" PagePath="/content/infiniti_master/ar_ME/index/vehicles/new-vehicles/Q60-Coupe-UK-2014/features">
            <PageURL ForPreviewOnly="True" NeedTranslation="False">http://author.prod.heliosnissan.net/content/infiniti_master/ar_ME/index/vehicles/new-vehicles/Q60-Coupe-UK-2014/features.html</PageURL>
            <PropertyContents>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content" PropertyName="jcr:title">Features</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader" PropertyName="txTitle">Features</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader/panel/freeEditorial/contentzone_5f48" PropertyName="txLinkTitle">Performance-and-Safety</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/pageHeader/panel/freeEditorial/contentzone_5f48" PropertyName="txTitle">Performance and Safety</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns12bleed_95a/col1-par/image_2c45" PropertyName="txAlt">Interior passenger sun flare</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns6_2e24/col1-par/image_4ca9" PropertyName="txBody">&lt;p&gt;Electronic Brake Force Distribution adjusts the amount of brake force applied to the front and rear wheels, improving performance and diminishing body motion. &amp;nbsp;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns6_2e24/col1-par/image_4ca9" PropertyName="txTitle">STABILITY WHILE STOPPING</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col1-par/image_3af8" PropertyName="txBody">&lt;p&gt;Intelligent Cruise Control (ICC) helps you look ahead and intuitively slows you down when traffic in front of you slows down. When the way is clear, it automatically accelerates back to your desired speed. For less effort, more ease.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col1-par/image_3af8" PropertyName="txTitle">Intelligent Cruise Control (ICC)</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col1-par/image_3af8/previewImage" PropertyName="txAlt">Frnt DS action</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col2-par/image_a04b" PropertyName="txBody">&lt;p&gt;Ultra high-strength steel, used in areas critical to preserving your safety, offers more than twice the tensile strength of conventional steel, for added resiliency and lighter weight.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col2-par/image_a04b" PropertyName="txTitle">STRONGER AND LIGHTER</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col2-par/image_a04b/previewImage" PropertyName="txAlt">Low Angle Rear</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col3-par/image_c84c" PropertyName="txBody">&lt;p&gt;When reversing, the RearView Monitor displays coloured guidelines to give you an accurate sense of how close you are to objects behind you, and adjusts as you turn to show your path — so you're always in control.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col3-par/image_c84c" PropertyName="txTitle">RearView Monitor</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/columns444_2f54/col3-par/image_c84c/previewImage" PropertyName="txAlt">Frnt DS location with talent</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_c69d/carousel-col1-par/image_a359" PropertyName="txBody">&lt;p&gt;Electronic Brake Force Distribution adjusts the amount of brake force applied to the front and rear wheels, improving performance and diminishing body motion.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_c69d/carousel-col1-par/image_a359" PropertyName="txTitle">STABILITY WHILE STOPPING</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_c69d/carousel-col1-par/image_a359/previewImage" PropertyName="txAlt">Rear overhead action</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_9926/carousel-col1-par/image_e9d5" PropertyName="txBody">&lt;p&gt;Intelligent Cruise Control (ICC) helps you look ahead and intuitively slows you down when traffic in front of you slows down. When the way is clear, it automatically accelerates back to your desired speed. For less effort, more ease.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_9926/carousel-col1-par/image_e9d5" PropertyName="txTitle">Intelligent Cruise Control (ICC)</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_9926/carousel-col1-par/image_e9d5/previewImage" PropertyName="txAlt">Navi</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_e52/carousel-col1-par/image_ec4c" PropertyName="txBody">&lt;p&gt;Ultra high-strength steel, used in areas critical to preserving your safety, offers more than twice the tensile strength of conventional steel, for added resiliency and lighter weight.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_e52/carousel-col1-par/image_ec4c" PropertyName="txTitle">STRONGER AND LIGHTER</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_e52/carousel-col1-par/image_ec4c/previewImage" PropertyName="txAlt">Detail of Climate Control Vent</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_2747/carousel-col1-par/image_260d" PropertyName="txBody">&lt;p&gt;When reversing, the RearView Monitor displays coloured guidelines to give you an accurate sense of how close you are to objects behind you, and adjusts as you turn to show your path — so you're always in control.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_2747/carousel-col1-par/image_260d" PropertyName="txTitle">RearView Monitor</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/columns/contentcarousel_23a1/carousel-columns/columns6_2747/carousel-col1-par/image_260d/previewImage" PropertyName="txAlt">Rear 3/4 detail</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/title" PropertyName="txBody">The 3.7-litre V6 combines visionary technology and dynamic thrust to reshape how movement is felt. It’s a revelation in acceleration. From the first moment of movement, you know everything has changed. The visceral intensity of its hard-charging, class-leading 329-hp is transformed by the rushing wave of acceleration swell that makes performance feel as effortless as it does limitless. It’s an experience brought to life by exclusive VVEL technology that continually adjusts intake valve lift and timing, delivering a quicker response and a broader torque curve, even while improving economy and emissions. Advanced technologies continuously monitor your surroundings for added peace mind on every journey. </PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/title" PropertyName="txTitle">Performance and Safety</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_5f48/title" PropertyName="txSubTitle">3.7-LITER V6 VVEL ENGINE</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88" PropertyName="txCollapsedCTA">Show more options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88" PropertyName="txExpandedCTA">Show less options</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns6_d894/col1-par/image_a560" PropertyName="txBody">&lt;p&gt;Infiniti Intelligent Key customises your driving experience without ever leaving your pocket or purse. Everything from your seat position, to navigation, climate and audio preferences, to performance and steering settings will be automatically set for you as you approach the Infiniti Q60.&amp;nbsp;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns6_d894/col1-par/image_a560" PropertyName="txTitle">A personalised experience</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col1-par/image_c9b4" PropertyName="txBody">&lt;p&gt;Our Infiniti Bose® Premium Sound System envelops you, creating depth and ambience for a wider, more immersive sound. With 13 speakers specially arranged inside your Q60 Coupé, sound washes through the cabin for greater audio entertainment.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col1-par/image_c9b4" PropertyName="txTitle">Infiniti Bose® Premium Sound System</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col1-par/image_c9b4/previewImage" PropertyName="txAlt">speaker detail</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col2-par/image_f95" PropertyName="txBody">&lt;p&gt;The Advanced Climate Control System actively cleans the air inside the cabin and removes up to 99.5% of allergens. It will also sense outside fumes and automatically close the vents, meaning your air and interior stay fresh.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col2-par/image_f95" PropertyName="txTitle">Advanced Climate Control System</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col2-par/image_f95/previewImage" PropertyName="txAlt">Detail of Climate Control Vent</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col3-par/image_5d87" PropertyName="txBody">&lt;p&gt;The Infiniti Hard Drive Navigation System features an elevated and realistic Birdview™ perspective with 3D building graphics to help you easily reach your destination.&lt;br&gt;&lt;/p&gt;</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col3-par/image_5d87" PropertyName="txTitle">Infiniti Hard Drive Navigation System</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/columns/columns444_cbd9/col3-par/image_5d87/previewImage" PropertyName="txAlt">Navi</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/title" PropertyName="txBody">With advanced technologies, Infiniti InSuite™ anticipates your needs, simplifies tasks and allows you to enjoy the ride in complete comfort.</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/contentzone_1f88/title" PropertyName="txTitle">Entertainment /  Comfort</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_f328/col1-par/linkspanel_4d44" PropertyName="txHeadline">start your journey</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_f328/col1-par/linkspanel_4d44/cta1" PropertyName="txText">performance</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_f328/col1-par/linkspanel_4d44/cta2" PropertyName="txText">accessories</PropertyContent>
                <PropertyContent IsMultipleValue="No" NodePath="jcr:content/freeEditorial/columns12bleed_f328/col1-par/linkspanel_4d44/cta3" PropertyName="txText">prices &amp; specifications</PropertyContent>